[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]  # line length via formatter, niet via linter blokkeren

[tool.ruff.format]
docstring-code-format = true
