name: AutoFix style (ruff)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure pyproject (ruff config)
        run: |
          if [ ! -f pyproject.toml ]; then
            cat > pyproject.toml <<'TOML'
            [tool.ruff]
            line-length = 100
            target-version = "py311"
            # We willen fouten juist fixen; geen blanket ignores.
            select = ["E", "F", "I"]
            # Laat import-sort ook meteen netjes doen
            [tool.ruff.format]
            docstring-code-format = true
            TOML
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Ruff auto-fix (utils, pages, home.py)
        run: |
          set -e
          echo "Before fix:"
          ruff check utils pages home.py || true
          # Fix in-place
          ruff check --fix utils pages home.py
          echo "After fix:"
          ruff check utils pages home.py || true

      - name: Commit & push (fallback if main protected)
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "ℹ️ Geen wijzigingen om te committen."
          else
            git commit -m "style: ruff auto-fix (autogenerated)"
            if git push origin HEAD:main; then
              echo "✅ Auto-fix gecommit naar main."
            else
              echo "ℹ️ main beschermd of non-fast-forward. Gebruik fallback branch."
              TS=$(date +%Y%m%d-%H%M%S)
              BR="autofix/ruff-${TS}"
              git branch -f "$BR"
              git checkout "$BR"
              git push -u origin "$BR"
              echo "::notice title=Vergelijk & merge::https://github.com/${GITHUB_REPOSITORY}/compare/${BR}?expand=1"
            fi
          fi

      - name: Final ruff check (fail on remaining issues)
        run: |
          ruff check utils pages home.py --output-format=github
