name: "Panic Button: Restore materials_db.csv (guardrails)"

on:
  workflow_dispatch:
    inputs:
      snapshot:
        description: 'Snapshot: "latest", "YYYYMMDD" of bestandsnaam (materials_YYYYMMDD.csv)'
        required: false
        default: "latest"
      dry_run:
        description: "Alleen diff tonen? (true/false)"
        required: false
        default: "false"
      threshold_pct:
        description: "Drempel als fractie (0.40 = 40%)"
        required: false
        default: "0.40"
      min_anomalies:
        description: "Min. aantal hits boven drempel om te blokkeren"
        required: false
        default: "10"
      force:
        description: "Forceer ondanks anomaliën? (true/false)"
        required: false
        default: "false"

permissions:
  contents: write

jobs:
  restore:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install pandas
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run restore (guardrails)
        env:
          SNAPSHOT:      ${{ github.event.inputs.snapshot }}
          DRY_RUN:       ${{ github.event.inputs.dry_run }}
          THRESHOLD_PCT: ${{ github.event.inputs.threshold_pct }}
          MIN_ANOMALIES: ${{ github.event.inputs.min_anomalies }}
          FORCE:         ${{ github.event.inputs.force }}
        run: |
          python tools/restore_materials_from_history.py

      - name: Commit & push (if changed and not dry-run)
        if: ${{ github.event.inputs.dry_run != 'true' }}
        shell: bash
        run: |
          set -e
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/materials_db.csv || true
            git add data/history/*.csv || true
            git commit -m "restore(materials): ${{
              github.event.inputs.snapshot
            }} (thr=${{ github.event.inputs.threshold_pct }}, min=${{ github.event.inputs.min_anomalies }}, force=${{ github.event.inputs.force }})"
            if git push origin HEAD:main; then
              echo "Pushed to main."
            else
              TS=$(date +%Y%m%d-%H%M%S)
              BR="restore/${TS}"
              git switch -c "$BR"
              git push -u origin "$BR"
              echo "::notice title=Open Pull Request::https://github.com/${GITHUB_REPOSITORY}/compare/${BR}?expand=1"
            fi
          else
            echo "No changes to commit."
          fi

      - name: Upload artifacts (materials + history)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: restore-output
          path: |
            data/materials_db.csv
            data/history/
          if-no-files-found: warn
