name: Unzip and Commit (Safe)
on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip file
        run: |
          unzip -o Cost-Forge-2.2-full.zip -d extracted
          rm Cost-Forge-2.2-full.zip

      - name: Copy files except .github
        run: |
          shopt -s dotglob
          for f in extracted/*; do
            if [ "$(basename "$f")" = ".github" ]; then
              echo "Skipping .github folder"
            else
              cp -r "$f" ./
            fi
          done
          rm -rf extracted

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzipped and committed contents (skip .github)"
          git push
