name: Weekly Market Update

on:
  schedule:
    - cron: "0 5 * * 1"   # elke maandag 05:00 UTC
  workflow_dispatch:      # handmatig starten

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps (pandas only)
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run market update
        run: |
          python tools/update_materials_from_market.py

      - name: Commit & push (only if changed)
        shell: bash
        run: |
          set -e
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/materials_db.csv
            git commit -m "chore: weekly market update (materials_db.csv)"
            # push naar main of fallback branch als main protected is
            if git push origin HEAD:main; then
              echo "Pushed to main."
            else
              TS=$(date +%Y%m%d-%H%M%S)
              BR="market-update/${TS}"
              git switch -c "$BR"
              git push -u origin "$BR"
              echo "::notice title=Open Pull Request::https://github.com/${GITHUB_REPOSITORY}/compare/${BR}?expand=1"
            fi
          else
            echo "No changes to commit."
          fi
